### ISSUE TITLE
bug: component does not respect safe area on iOS

### ISSUE THREAD

**Issue by Maartenb111** [capawesome-team/capacitor-datetime-picker#4]
**Plugin version:**

0.2.1

**Platform(s):**

iOS

**Current behavior:**

The component (when using datetime) does not respect the bottom safe area and is being cut of by the roundness of the screen (see attached photo). The bigger the device font-size, the greater the issue.

![IMG_1657](https://user-images.githubusercontent.com/18197337/218756753-0a830993-d062-43ab-a68f-821f281a1c73.jpg)

![IMG_1658](https://user-images.githubusercontent.com/18197337/218759555-40842d92-464f-4de7-a5f2-9924da810b5e.jpg)

**Expected behavior:**

Only use the safe area so the user can properly view and click the component button. Also in landscape mode.

![safe](https://user-images.githubusercontent.com/18197337/218757127-3ab582de-f45e-4a4a-a5c7-a80d88b00532.png)

**Steps to reproduce:**

Just open the picker on an iPhone with a rounded screen.

**Capacitor doctor:**

💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.6.3
  @capacitor/core: 4.6.3
  @capacitor/android: 4.6.3
  @capacitor/ios: 4.6.3

Installed Dependencies:

  @capacitor/cli: 4.6.2
  @capacitor/core: 4.6.2
  @capacitor/android: 4.6.2
  @capacitor/ios: 4.6.2

[success] iOS looking great! 👌
[success] Android looking great! 👌

**Comment by robingenz** [comment]
This is fixed in version `0.2.2`:

<img src="https://user-images.githubusercontent.com/13857929/218871034-52270cf7-0e07-4500-b124-fcf8843d807f.jpeg" width="350"/>

**Comment by robingenz** [comment]
**Note**: It is currently not recommended to use the `datetime` mode in landscape format on devices with small screens (e.g. iPhone), as the calendar requires too much height.

**Comment by Maartenb111** [comment]
Thanks a lot for the quick fix Robin! Keep up the good work.
